// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7OSaqUA1tMyDmLiAXGgyt0S-MCDN5Fqw',
    appId: '1:691120808473:web:657ee2d491515f47a4c088',
    messagingSenderId: '691120808473',
    projectId: 'flutter-5118a',
    authDomain: 'flutter-5118a.firebaseapp.com',
    storageBucket: 'flutter-5118a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHaLJuolxf0Zm8nFhXrxuy4rAC4XtTao',
    appId: '1:691120808473:android:835b014e5f833ffca4c088',
    messagingSenderId: '691120808473',
    projectId: 'flutter-5118a',
    storageBucket: 'flutter-5118a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFXruZ5jb5loAiOjOSzV7g8rFTBya1Xg',
    appId: '1:691120808473:ios:635099fc6aa3adc4a4c088',
    messagingSenderId: '691120808473',
    projectId: 'flutter-5118a',
    storageBucket: 'flutter-5118a.appspot.com',
    iosClientId: '691120808473-ocoh6vl4a5g2h2q8ffpbhqdm358rr8s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFXruZ5jb5loAiOjOSzV7g8rFTBya1Xg',
    appId: '1:691120808473:ios:8b7fb4cc9cb4c11ea4c088',
    messagingSenderId: '691120808473',
    projectId: 'flutter-5118a',
    storageBucket: 'flutter-5118a.appspot.com',
    iosClientId: '691120808473-js8qlj7jorbto7uqg0mgc2t0a7ini28v.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
